#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  9 22:27:05 2018

@author: 
"""

import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
 
width, height = 1000, 750
famWidth, famHeight, famYard = 80,80,20
bungWidth, bungHeight, bungYard = 100, 75, 30
mansWidth, mansHeight, mansYard = 110, 105, 60
famPrice, bungPrice, mansPrice = 285000, 399000, 610000
famInc, bungInc, mansInc = 0.03, 0.04, 0.06
famPercentage, bungPercentage, mansPercentage = .5, .3, .2
waterSize = .2


Matrix = [[.5 for x in range(width)] for y in range(height)]

def placeYard(startX, startY, landMap):
   # hType = "famHome"
    yardSize = 50
   
    for h in range(0, yardSize) :
        for i in range(startX-h, startX+famWidth+h):
            landMap[i][startY-h] = .1
            landMap[i][startY+famHeight+h] = .1
        
        for j in range(startY-h, startY+famHeight+h):
            landMap[startX-h][j] = .1
            landMap[startX+famWidth+h-1][j+1] = .1

def placeFamHome(startX, startY, landMap):
 #   if(checkProperty(startX, startY, "famHome", landMap)):
    placeYard(startX, startY, landMap)      
    
    for i in range(startX, startX+famWidth):
        for j in range(startY, startY+famHeight):
            landMap[i][j] = 0
            
def placeBungalow(startX, startY, landMap):
    if(checkProperty(startX, startY, "bungalow", landMap)):
        for i in range(startX, startX+bungWidth):
            for j in range(startY, startY+bungHeight):
                landMap[i][j] = 0
            
def placeMansion(startX, startY, landMap):
    if(checkProperty(startX, startY, "mansion", landMap)):
        for i in range(startX, startX+mansWidth):
            for j in range(startY, startY+mansHeight):
                landMap[i][j] = 0
            
def checkProperty(startX, startY, hType, landMap):
    if (hType == "famHome"):
        w,h = famWidth, famHeight
    if (hType == "bungalow"):
        w,h = bungWidth, bungHeight
    if (hType == "mansion"):
        w,h = bungWidth, bungHeight
    
    if(checkOutofBounds(startX, startY)):
        return False
    
    for i in range(startX, startX+w):
        for j in range(startY, startY+h):
            if(landMap[i][j] == 0) or (landMap[i][j] == .1):
                return False
    return True

#yard
def checkOutofBounds(x,y):
    return (x > width - 350) or (x<50) or (y > height - 350) or (y<50)

def fillMap(landMap):
    for i in range(0,width-150):
        for j in range(0,height-150):
            placeMansion(i,j,landMap)
            placeBungalow(i,j,landMap)
            placeFamHome(i,j,landMap)
    
#insert family home
placeFamHome(400,400,Matrix)

        
plt.imshow(Matrix, cmap='summer_r', interpolation='nearest')
plt.show()

